In [2]:
Creacion
Atributos
Funciones
Indexacion particion iteracion 
operaciones 
metodos

SyntaxError: invalid syntax (<ipython-input-2-44d4305afe27>, line 4)

## NumPy

NumPy es la principal biblioteca de la computación científica en python. El corazón de NumPy es la clase ndarray con esta podemos realizar diferentes tipos de operaciones matemáticas como:
* Algebra Lineal Basica
* Operaciones Lógicas
* Ordenamiento
* Operaciones estadísticas básicas
* Transformaciones discretas de Fourier

### Arreglo 
Es una colección de elementos de un mismo tipo de dato. La dimensión de un arreglo es la cantidad de indices necesarias para acceder a un elemento del arreglo.

![](../img/img_00.jpg)

### ndarray

Para la creación de un arreglo en NumPy, se utiliza la clase ndarray.



In [3]:
# Importamos NumPy
import numpy as np # Por convención se usa el pseudonimo np

# Recibe como parametro una lista
arreglo = np.array([[1, 2],
                    [3, 4]])

lista = [[3, 4],[5, 6]]

arreglo_lista = np.array(lista)

print(arreglo)

[[1 2]
 [3 4]]


Los atributos más importantes del ndarray son los siguientes.

| Atributo | Descripción                                                    |
|----------|----------------------------------------------------------------|
| ndim     | Número de dimensiones del arreglo                              |
| size     | Número total de elementos del arreglo.                         |
| shape    | Tupla de la cantidad de elementos de cada dimensión.           |
| dtype    | Tipo de dato de los elementos arreglo(Tipos propios de numpy). |

In [4]:

arreglo_1 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]]) 

print("Número de dimensiones del arreglo: {}".format(arreglo_1.ndim))
print("Número total de elementos del arreglo: {}".format(arreglo_1.size))
print("Cantidad de elementos de cada dimensión: {}".format(arreglo_1.shape))
print("Tipo de dato de los elementos arreglo: {}".format(arreglo_1.dtype))

Número de dimensiones del arreglo: 2
Número total de elementos del arreglo: 9
Cantidad de elementos de cada dimensión: (3, 3)
Tipo de dato de los elementos arreglo: int32


### Funciones de NumPy

Funciones para la creación de ndarrays rellenados.

In [5]:
# Creación de matriz unidimensional 
arreglo_rango_0 = np.arange(9)
print("Arreglo de 0 a 8: {} ".format(arreglo_rango_0))

# Creación de matriz unidimensional con principio en 0, final en 18 y recorriendo de 2 en 2
arreglo_rango_1 = np.arange(0, 18, 2) # Con arange los elementos del arreglo son enteros
print("Arreglo de 0 a 16 de 2 en 2: {}".format(arreglo_rango_1))

# Creacion de matriz con linspace de un limite n a un limite m con k elementos
# np.linspace(n, m , k)
arreglo_espacio_lineal = np.linspace(0, 5, 9) # Son flotantes
print("Arreglo de 9 elementos segmentados uniformemente entre 0 y 5 : {}".format(arreglo_espacio_lineal))

# Por default se generan 50 elementos
arreglo_espacio_default = np.linspace(0, 5)
print("Arreglo de linspace sin especificar cantidad de elementos: \n{}".format(arreglo_espacio_default))

# Creacion de un arreglo el cual sus elementos son uno
arreglo_unos = np.ones((3,3))
print("Arreglo de unos: \n{}".format(arreglo_unos))

# Creacion de un arreglo el cual sus elementos son cero
arreglo_ceros = np.zeros((3,3))
print("Arreglo de ceros: \n{}".format(arreglo_ceros))

Arreglo de 0 a 8: [0 1 2 3 4 5 6 7 8] 
Arreglo de 0 a 16 de 2 en 2: [ 0  2  4  6  8 10 12 14 16]
Arreglo de 9 elementos segmentados uniformemente entre 0 y 5 : [0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375 5.   ]
Arreglo de linspace sin especificar cantidad de elementos: 
[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
Arreglo de unos: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arreglo de ceros: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Indexación, partición e iteración

Para acceder a los elementos de un arreglo utilizamos indices, muy similar a las listas en python.

Recordemos que los indices de un arreglo en programación, empiezan en el número 0.

![](../img/img_01.png)

#### Indexación, partición e iteración en arreglos unidimensionales

In [31]:
A = np.arange(20)
# Para hacer referencia al indice, escribimos el nombre del arreglo y entre corchetes el número del indice
# Primer elemento del arreglo A
print(A[0])

#Imprimimos todo el arreglo
print(A[:])

# También podemos usar indices negativos indicando que es el ultimo elemento del arreglo
print(A[-1]) # A[-2] seria el penultimo elemento y así sucesivamente

# También podemos recorrer el arreglo con el operador ':'
print(A[1:6]) # Imprimira los elementos del 1 al 5. En general si arreglo[n:m] recorrerá de n a m-1

print(A[:6]) # Imprime del elemento 0 al elemento 5

print(A[2:]) # Imprime del elemento 2 en adelante

# Al igual que el metodo arange podemos definir como recorremos el arreglo 
print(A[1:6:2]) # De 2 en 2

# Tambien podemos recorrer de izquiera a derecha
print(A[5:0:-1]) # Del elemento 6 al elemento 2

# Un arreglo tambien puede ser recorrido con un ciclo for each
for e in A:
    print(e)

0
19
[1 2 3 4 5]
[0 1 2 3 4 5]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 3 5]
[5 4 3 2 1]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


#### Indexación, partición e iteración en arreglos multidimensionales

Las listas de listas serian homólogas a los arreglos multidimensionales, pero la diferencia es la forma de indexar en una lista de lista utilizamos un par de corchetes '[ ]' por cada indice. En el caso de los ndarrays utilizamos solo un par de corchetes y separamos por comas dentro de ese corchete los indices.  

In [33]:
lista = []

for m in range(1, 10, 3):
    lista.append([m, m+1, m+2])

# Para acceder al elemento en una lista(0,0)
print(lista[0][0])

arreglo_m = np.array(lista)

# Para acceder al elemento en un arreglo(0,0)
print(arreglo[0, 0])

1
1


In [46]:
# Podemos utilizar las mismas técnicas de iteración del arreglo unidimensional a cada dimension del arreglo
print(arreglo_m)
print(arreglo_m[:, :2]) # [Imprimir todas las filas : , imprimir de la columna 0 hasta la 1]
print(arreglo_m[:2, :2])
print("")
print(arreglo_m[0]) # Si usamos unicamente un indice, estaremos imprimiendo la fila a la que hacemos referencia
print("")
print(arreglo_m[..., 2]) # Tambien si queremos imprimir unicamente una fila podemos usar los tres puntos ...
print("")

# La iteracion sobre arreglos multidimensionales es sobre el primer eje, en este caso las filas
for fila in arreglo_m:
    print(fila)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[1 2]
 [4 5]]

[1 2 3]

[3 6 9]

[1 2 3]
[4 5 6]
[7 8 9]


### Operaciones

Es una de las razones más importantes por las cuales el ndarray de NumPy es tan utilizado en computación científica.

In [68]:
# Realizar una suma de matrices o arreglos, no es tan sencillo realizar con listas

# Suma de listas de dos dimensiones
def sumar(lista_0, lista_1):
    suma = []
    # Verificamos que las dimensiones sean del mismo tamaño
    if len(lista_0) == len(lista_1):
        
        if  len(lista_0[0]) == len(lista_1[0]):
            
            for i in range(len(lista_0)):
            
                temporal = []
                
                for k in range(len(lista_0[0])):
                    temporal.append(lista_0[i][k] + lista_1[i][k])
                
                suma.append(temporal)
    
    return suma


In [71]:
# Suma 
lista_0 = []
lista_1 = []

for k in range(1, 9, 2):
    if k <= 4:
        lista_0.append([k, k+1])
    else:
        lista_1.append([k, k+1])

print(lista_0)
print(lista_1)

print(sumar(lista_0, lista_1))

# Para realizar una simple suma tuvimos que crear una función para unicamente el caso especial de arreglos de dimensión 2

array_0 = np.array(lista_0)
array_1 = np.array(lista_1)

# Ahora para realizar una suma en NumPy solo hay que usar el operador '+'
# Para poder realizar estas operaciones los arreglos deben tener el mismo shape, numero de elementos por dimension
suma_array = array_0 + array_1

# Resta 
sustraccion_array = array_0 - array_1

print(suma_array)
print(sustraccion_array)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
[[6, 8], [10, 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


#### Multplicación

Para realizar mutliplicacón de arreglos se utiliza el producto de Hadamard o mutliplicación element-wise(Elemento por elemento)

![](../img/img_03.png)

![](../img/img_02.png)

Y la divsion de Hadamard se denota así:

![](../img/img_04.png)

In [78]:
# Para poder realizar estas operaciones los arreglos deben tener el mismo shape, numero de elementos por dimension
array_producto = array_0 * array_1 
print(array_producto)

division_array = array_0 / array_1
print(division_array)

# Multiplicación por escalar
print(2 * array_producto)
print(2 + array_producto)
print(2 - array_producto)
print(array_producto - 2)
print(2 / array_producto)
print(array_producto / 2)


[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[10 24]
 [42 64]]
[[ 7 14]
 [23 34]]
[[ -3 -10]
 [-19 -30]]
[[ 3 10]
 [19 30]]
[[0.4        0.16666667]
 [0.0952381  0.0625    ]]
[[ 2.5  6. ]
 [10.5 16. ]]


### Más funciones 
