## NumPy

NumPy es la principal biblioteca de la computación científica en python. El corazón de NumPy es la clase ndarray con esta podemos realizar diferentes tipos de operaciones matemáticas como:
* Algebra Lineal Basica
* Operaciones Lógicas
* Ordenamiento
* Operaciones estadísticas básicas
* Transformaciones discretas de Fourier

### Arreglo 
Es una colección de elementos de un mismo tipo de dato. La dimensión de un arreglo es la cantidad de indices necesarias para acceder a un elemento del arreglo.

![](../img/img_00.jpg)

### ndarray

Para la creación de un arreglo en NumPy, se utiliza la clase ndarray.



In [2]:
# Importamos NumPy
import numpy as np # Por convención se usa el pseudonimo np

# Recibe como parametro una lista
arreglo = np.array([[1, 2],
                    [3, 4]])

lista = [[3, 4],[5, 6]]

arreglo_lista = np.array(lista)

print(arreglo)

[[1 2]
 [3 4]]


Los atributos más importantes del ndarray son los siguientes.

| Atributo | Descripción                                                    |
|----------|----------------------------------------------------------------|
| ndim     | Número de dimensiones del arreglo                              |
| size     | Número total de elementos del arreglo.                         |
| shape    | Tupla de la cantidad de elementos de cada dimensión.           |
| dtype    | Tipo de dato de los elementos arreglo(Tipos propios de numpy). |

In [4]:

arreglo_1 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]]) 

print("Número de dimensiones del arreglo: {}".format(arreglo_1.ndim))
print("Número total de elementos del arreglo: {}".format(arreglo_1.size))
print("Cantidad de elementos de cada dimensión: {}".format(arreglo_1.shape))
print("Tipo de dato de los elementos arreglo: {}".format(arreglo_1.dtype))

Número de dimensiones del arreglo: 2
Número total de elementos del arreglo: 9
Cantidad de elementos de cada dimensión: (3, 3)
Tipo de dato de los elementos arreglo: int32


### Funciones de NumPy

Funciones para la creación de ndarrays rellenados.

In [31]:
# Creación de matriz unidimensional 
arreglo_rango_0 = np.arange(9)
print("Arreglo de 0 a 8: {} ".format(arreglo_rango_0))

# Creación de matriz unidimensional con principio en 0, final en 18 y recorriendo de 2 en 2
arreglo_rango_1 = np.arange(0, 18, 2) # Con arange los elementos del arreglo son enteros
print("Arreglo de 0 a 16 de 2 en 2: {}".format(arreglo_rango_1))

# Creacion de matriz con linspace de un limite n a un limite m con k elementos
# np.linspace(n, m , k)
arreglo_espacio_lineal = np.linspace(0, 5, 9) # Son flotantes
print("Arreglo de 9 elementos segmentados uniformemente entre 0 y 5 : {}".format(arreglo_espacio_lineal))

# Por default se generan 50 elementos
arreglo_espacio_default = np.linspace(0, 5)
print("Arreglo de linspace sin especificar cantidad de elementos: \n{}".format(arreglo_espacio_default))

# Creacion de un arreglo el cual sus elementos son uno
arreglo_unos = np.ones((3,3))
print("Arreglo de unos: \n{}".format(arreglo_unos))

# Creacion de un arreglo el cual sus elementos son cero
arreglo_ceros = np.zeros((3,3))
print("Arreglo de ceros: \n{}".format(arreglo_ceros))

# Cracion de una matriz sin entradas inicializadas, NumPy les asigna valores aleatorios
arreglo_vacio = np.empty((2, 2))

Arreglo de 0 a 8: [0 1 2 3 4 5 6 7 8] 
Arreglo de 0 a 16 de 2 en 2: [ 0  2  4  6  8 10 12 14 16]
Arreglo de 9 elementos segmentados uniformemente entre 0 y 5 : [0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375 5.   ]
Arreglo de linspace sin especificar cantidad de elementos: 
[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
Arreglo de unos: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arreglo de ceros: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Indexación, partición e iteración

Para acceder a los elementos de un arreglo utilizamos indices, muy similar a las listas en python.

Recordemos que los indices de un arreglo en programación, empiezan en el número 0.

![](../img/img_01.png)

#### Indexación, partición e iteración en arreglos unidimensionales

In [31]:
A = np.arange(20)
# Para hacer referencia al indice, escribimos el nombre del arreglo y entre corchetes el número del indice
# Primer elemento del arreglo A
print(A[0])

#Imprimimos todo el arreglo
print(A[:])

# También podemos usar indices negativos indicando que es el ultimo elemento del arreglo
print(A[-1]) # A[-2] seria el penultimo elemento y así sucesivamente

# También podemos recorrer el arreglo con el operador ':'
print(A[1:6]) # Imprimira los elementos del 1 al 5. En general si arreglo[n:m] recorrerá de n a m-1

print(A[:6]) # Imprime del elemento 0 al elemento 5

print(A[2:]) # Imprime del elemento 2 en adelante

# Al igual que el metodo arange podemos definir como recorremos el arreglo 
print(A[1:6:2]) # De 2 en 2

# Tambien podemos recorrer de izquiera a derecha
print(A[5:0:-1]) # Del elemento 6 al elemento 2

# Un arreglo tambien puede ser recorrido con un ciclo for each
for e in A:
    print(e)

0
19
[1 2 3 4 5]
[0 1 2 3 4 5]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 3 5]
[5 4 3 2 1]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


#### Indexación, partición e iteración en arreglos multidimensionales

Las listas de listas serian homólogas a los arreglos multidimensionales, pero la diferencia es la forma de indexar en una lista de lista utilizamos un par de corchetes '[ ]' por cada indice. En el caso de los ndarrays utilizamos solo un par de corchetes y separamos por comas dentro de ese corchete los indices.  

In [33]:
lista = []

for m in range(1, 10, 3):
    lista.append([m, m+1, m+2])

# Para acceder al elemento en una lista(0,0)
print(lista[0][0])

arreglo_m = np.array(lista)

# Para acceder al elemento en un arreglo(0,0)
print(arreglo[0, 0])

1
1


In [46]:
# Podemos utilizar las mismas técnicas de iteración del arreglo unidimensional a cada dimension del arreglo
print(arreglo_m)
print(arreglo_m[:, :2]) # [Imprimir todas las filas : , imprimir de la columna 0 hasta la 1]
print(arreglo_m[:2, :2])
print("")
print(arreglo_m[0]) # Si usamos unicamente un indice, estaremos imprimiendo la fila a la que hacemos referencia
print("")
print(arreglo_m[..., 2]) # Tambien si queremos imprimir unicamente una fila podemos usar los tres puntos ...
print("")

# La iteracion sobre arreglos multidimensionales es sobre el primer eje, en este caso las filas
for fila in arreglo_m:
    print(fila)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[1 2]
 [4 5]]

[1 2 3]

[3 6 9]

[1 2 3]
[4 5 6]
[7 8 9]


### Operaciones

Es una de las razones más importantes por las cuales el ndarray de NumPy es tan utilizado en computación científica.

In [68]:
# Realizar una suma de matrices o arreglos, no es tan sencillo realizar con listas

# Suma de listas de dos dimensiones
def sumar(lista_0, lista_1):
    suma = []
    # Verificamos que las dimensiones sean del mismo tamaño
    if len(lista_0) == len(lista_1):
        
        if  len(lista_0[0]) == len(lista_1[0]):
            
            for i in range(len(lista_0)):
            
                temporal = []
                
                for k in range(len(lista_0[0])):
                    temporal.append(lista_0[i][k] + lista_1[i][k])
                
                suma.append(temporal)
    
    return suma


In [71]:
# Suma 
lista_0 = []
lista_1 = []

for k in range(1, 9, 2):
    if k <= 4:
        lista_0.append([k, k+1])
    else:
        lista_1.append([k, k+1])

print(lista_0)
print(lista_1)

print(sumar(lista_0, lista_1))

# Para realizar una simple suma tuvimos que crear una función para unicamente el caso especial de arreglos de dimensión 2

array_0 = np.array(lista_0)
array_1 = np.array(lista_1)

# Ahora para realizar una suma en NumPy solo hay que usar el operador '+'
# Para poder realizar estas operaciones los arreglos deben tener el mismo shape, numero de elementos por dimension
suma_array = array_0 + array_1

# Resta 
sustraccion_array = array_0 - array_1

print(suma_array)
print(sustraccion_array)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
[[6, 8], [10, 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


#### Multplicación

Para realizar mutliplicacón de arreglos se utiliza el producto de Hadamard o mutliplicación element-wise(Elemento por elemento)

![](../img/img_03.png)

![](../img/img_02.png)

Y la divsion de Hadamard se denota así:

![](../img/img_04.png)

In [78]:
# Para poder realizar estas operaciones los arreglos deben tener el mismo shape, numero de elementos por dimension
array_producto = array_0 * array_1 
print(array_producto)

division_array = array_0 / array_1
print(division_array)

# Multiplicación por escalar
print(2 * array_producto)
print(2 + array_producto)
print(2 - array_producto)
print(array_producto - 2)
print(2 / array_producto)
print(array_producto / 2)


[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[10 24]
 [42 64]]
[[ 7 14]
 [23 34]]
[[ -3 -10]
 [-19 -30]]
[[ 3 10]
 [19 30]]
[[0.4        0.16666667]
 [0.0952381  0.0625    ]]
[[ 2.5  6. ]
 [10.5 16. ]]


### Más funciones 


NumPy incluye funciones matemáticas para aplicarlas a los ndarrays, están funciones son aplicadas a cada elemento del arreglo.

In [26]:
 arreglo_fun = np.array([[2, 1],
                         [3, 4]])

# Funcion raiz cuadrada
print("Raiz cuadrada de los elementos del areglo: \n {}".format(np.sqrt(arreglo_fun)))

# Funcion max
print("Elemento mas grande del arreglo: {}".format(np.max(arreglo_fun)))
print("Elemento mas pequeño del arreglo: {}".format(np.min(arreglo_fun)))

Raiz cuadrada de los elementos del areglo: 
 [[1.41421356 1.        ]
 [1.73205081 2.        ]]
Elemento mas grande del arreglo: 4
Elemento mas pequeño del arreglo: 1


### Ejes

Los axis(ejes) de un arreglo de numpy son la orientación de los indices en el arreglo

![](../img/img_05.png)

In [23]:
# En la mayoría de las funciones podemos especificar a que eje (dimension) lo aplicaremos
print("Elementos mas grandes de cada columna:  {}".format(np.max(arreglo_fun, axis = 0))) # El axis(eje) 0 es el de las columnas
print("Elementos mas grandes de cada fila:  {}".format(np.max(arreglo_fun, axis = 1))) # El axis(eje) 1 es el de las filas

Raiz cuadrada de los elementos de la matriz: 
 [[1.41421356 1.        ]
 [1.73205081 2.        ]]
Elemento mas grande de la matriz: 4
Elemento mas pequeño de la matriz: 1
Elementos mas grandes de cada columna:  [3 4]
Elementos mas grandes de cada fila:  [2 4]


In [28]:
# Funcion argmax
print("Indice del elemento mas grande del arreglo: {}".format(np.argmax(arreglo_fun)))
print("Indices del elemento mas grande de las filas: {} se pueden interpretar como [0, 0] y [1, 1]".format(np.argmax(arreglo_fun, axis = 1)))
print("Indices del elemento mas grande de la matriz: {} se pueden interpretar como [1, 0] y [1, 1]".format(np.argmax(arreglo_fun, axis = 0)))


Indice del elemento mas grande del arreglo: 3
Indices del elemento mas grande de las filas: [0 1] se pueden interpretar como [0, 0] y [1, 1]
Indices del elemento mas grande de la matriz: [1 1] se pueden interpretar como [1, 0] y [1, 1]


In [52]:
# Multiplicacion común de matrices
arreglo1 = np.array([[2, 2],
                    [3, 8]])

arreglo2 = np.array([[3, 3],
                    [4, 9]])

print("Arreglo 1 \n {} \nArreglo 2\n {}".format(arreglo1, arreglo2))


print("Multiplicacion: \n",np.dot(arreglo1, arreglo2)) # Nos indica un error si las dimensiones no son compatibles

# Suma de los elementos
print(np.sum(arreglo1))
print(np.sum(arreglo1, axis = 0))

# Transpuesta
print("Arreglo transpuesto del arreglo 1 \n{}".format(np.transpose(arreglo1)))

# Media
print("Media de todos los elementos: {}".format(np.mean(arreglo1)))
print("Medias de las filas: {}".format(np.mean(arreglo1, axis = 1)))
print("Medias de las columnas: {}".format(np.mean(arreglo1, axis = 0)))

# Desviacion Estandar 
print("Desviación estandar de todos los elementos: {}".format(np.std(arreglo1)))
print("Desviaciónes estandar de las filas: {}".format(np.std(arreglo1, axis = 1)))
print("Desviaciónes estandar de las columnas: {}".format(np.std(arreglo1, axis = 0)))

# Varianza
print("Varianza de todos los elementos: {}".format(np.std(arreglo1)))
print("Varianzas de las filas: {}".format(np.std(arreglo1, axis = 1)))
print("Varianzas de las columnas: {}".format(np.std(arreglo1, axis = 0)))

# Matriz de Covarianza
print("Matriz de covarianza \n {} ".format(np.cov(arreglo1)))

# Ordenar los elementos
print("Arreglo ordenado \n {}".format(np.sort(arreglo1)))



Arreglo 1 
 [[2 2]
 [3 8]] 
Arreglo 2
 [[3 3]
 [4 9]]
Multiplicacion: 
 [[14 24]
 [41 81]]
15
[ 5 10]
Arreglo transpuesto del arreglo 1 
[[2 3]
 [2 8]]
Media de todos los elementos: 3.75
Medias de las filas: [2.  5.5]
Medias de las columnas: [2.5 5. ]
Desviación estandar de todos los elementos: 2.48746859276655
Desviaciónes estandar de las filas: [0.  2.5]
Desviaciónes estandar de las columnas: [0.5 3. ]
Varianza de todos los elementos: 2.48746859276655
Varianzas de las filas: [0.  2.5]
Varianzas de las columnas: [0.5 3. ]
Matriz de covarianza 
 [[ 0.   0. ]
 [ 0.  12.5]] 
Arreglo ordenado 
 [[2 2]
 [3 8]]


### Métodos

Metodos más comunes de los ndarray

In [58]:
arreglin = np.empty(10)

print("Arreglo {}".format(arreglin))


# Suma
print("Suma de los elementos{}".format(arreglin.sum()))

# Promedio
print("Promedio {}".format(arreglin.mean())) #Igual podemos utilizar la funcion mean

# Cambiar la forma del arreglo
print("Arreglo reestructurado:\n {}".format(arreglin.reshape((2, 5))))
print("Arreglo de nuevo :\n {}".format(arreglin))

# Cambiar la forma del arreglo de manera permanente 
arreglin.resize((2, 5))
print("Arreglo de nuevo : \n {}".format(arreglin))


Arreglo [8.90070286e-308 8.90088111e-308 1.11258192e-307 1.27946330e-307
 2.44770008e-307 8.90103559e-307 9.79098366e-307 1.11261027e-306
 1.24611470e-306 1.29061821e-306]
Suma de los elementos6.18053547048838e-306
Promedio 6.1805354704883795e-307
Arreglo reestructurado:
 [[8.90070286e-308 8.90088111e-308 1.11258192e-307 1.27946330e-307
  2.44770008e-307]
 [8.90103559e-307 9.79098366e-307 1.11261027e-306 1.24611470e-306
  1.29061821e-306]]
Arreglo de nuevo :
 [8.90070286e-308 8.90088111e-308 1.11258192e-307 1.27946330e-307
 2.44770008e-307 8.90103559e-307 9.79098366e-307 1.11261027e-306
 1.24611470e-306 1.29061821e-306]
Arreglo de nuevo : 
 [[8.90070286e-308 8.90088111e-308 1.11258192e-307 1.27946330e-307
  2.44770008e-307]
 [8.90103559e-307 9.79098366e-307 1.11261027e-306 1.24611470e-306
  1.29061821e-306]]
